#!/bin/bash
rm -rf dist
export PYTHONHASHSEED=22
#VERSION=`git describe --tags`
pyinstaller --noconfirm --ascii contrib/osx.spec
hdiutil create -fs HFS+ -volname "Electrum-GRS" -srcfolder dist/Electrum-GRS.app dist/electrum-grs-$VERSION.dmg

